name: maskrcnn

dependencies:
  - h5py=3.6.0=py39h7fe8675_0
  - opencv=4.6.0=py39h8794c10_2
  - pip:
      - imageio==2.22.4
      - imgaug==0.4.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - multiprocess==0.70.14
      - numpy==1.23.4
      - opencv-python==4.6.0.66
      - pandas==1.5.1
      - pyyaml==6.0
      - requests-oauthlib==1.3.1
      - scikit-image==0.19.3
      - scikit-learn==1.2.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.10.0
      - tensorflow-macos==2.10.0
      - tensorflow-metal==0.6.0